language: java

sudo: false

jdk:
  - oraclejdk8

script: mvn clean package

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6dbf6b6f4906b82799c5
    on_success: always
    on_failure: always
    on_start: never
